### PR TITLE
Added native for get level index

### PR DESCRIPTION
**Pull request by Franc1sco**

### CODE REVIEW

**Review by KillStr3aK — APPROVED** [review]
Thanks, didn’t thought about this.
Maybe I’ll add more features in the future.

**Comment by Franc1sco** [comment]
Also could be a good idea to use the same native and library for your store version in order to make it compatible too for my country flag plugin version.

**Comment by Franc1sco** [comment]
And can you merge or apply this changes to the main repo? I show that you approved it but not merged into the repository. For people could use this after now together with the country flag plugin. Thanks.

**Comment by KillStr3aK** [comment]
I wasn't at home so just approved it in the first hand

**Pull request merged**
